// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuMNSlOfC9cAa3jtsBBDgpEyBnWRKnwcI',
    appId: '1:794534839382:web:d99ef8da0cc05f8f7a67f7',
    messagingSenderId: '794534839382',
    projectId: 'chill-player-359704',
    authDomain: 'chill-player-359704.firebaseapp.com',
    storageBucket: 'chill-player-359704.appspot.com',
    measurementId: 'G-G2SZFD4JQN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDE-f1mp0KWRbid3Y3YmmY7BpQ8yxd1rJM',
    appId: '1:794534839382:android:bbe47cd0b73dda4a7a67f7',
    messagingSenderId: '794534839382',
    projectId: 'chill-player-359704',
    storageBucket: 'chill-player-359704.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8bMF432zCfJbZzpgUbSvDcVxl7hxDdFU',
    appId: '1:794534839382:ios:a541f1f960b35a547a67f7',
    messagingSenderId: '794534839382',
    projectId: 'chill-player-359704',
    storageBucket: 'chill-player-359704.appspot.com',
    iosClientId: '794534839382-9454k1800lkujk5mgrh4jfj0ks0vt4h4.apps.googleusercontent.com',
    iosBundleId: 'com.chilltime.chill.chill',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8bMF432zCfJbZzpgUbSvDcVxl7hxDdFU',
    appId: '1:794534839382:ios:67482a235e74fb4a7a67f7',
    messagingSenderId: '794534839382',
    projectId: 'chill-player-359704',
    storageBucket: 'chill-player-359704.appspot.com',
    iosClientId: '794534839382-o5q6cakrplqg12hodehuorn3ussbcb8h.apps.googleusercontent.com',
    iosBundleId: 'com.chilltime.chill',
  );
}
